name: Deploy to Firebase Functions
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCER_DASHBOARD }}' > $HOME/gcloud.json
      
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json


          