name: Deploy to Firebase Functions
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/firebase-functions-actions/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Cloud Functions
        run: cd functions && npm ci

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FUNCTIONS }}' > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json